=== ArcticaProject/vcxsrv/mesalib/src/mesa/main/APIspec.dtd
<!ELEMENT apispec (template|api)+>

<!ELEMENT api (category*, function*)>
<!ELEMENT category EMPTY>
<!ELEMENT function EMPTY>

<!ELEMENT template (proto, desc*)>
<!ELEMENT proto (return, (param|vector)*)>
<!ELEMENT return EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT vector (param*)>
<!ELEMENT desc ((value|range)*, desc*)>
<!ELEMENT value EMPTY>
<!ELEMENT range EMPTY>

<!ATTLIST api      name                NMTOKEN #REQUIRED
                   implementation      (true | false) "false">
<!ATTLIST category name                NMTOKEN #REQUIRED>
<!ATTLIST function name                NMTOKEN #REQUIRED
                   default_prefix      NMTOKEN "_mesa_"
                   external            (true | false) "false"
                   template            NMTOKEN #REQUIRED
                   gltype              CDATA #IMPLIED
                   vector_size         NMTOKEN #IMPLIED
                   expand_vector       (true | false) "false"
                   skip_desc           (true | false) "false">

<!ATTLIST template name                NMTOKEN #REQUIRED
                   direction           (set | get) "set">

<!ATTLIST return   type                CDATA #REQUIRED>
<!ATTLIST param    name                NMTOKEN #REQUIRED
                   type                CDATA #REQUIRED
                   hide_if_expanded    (true | false) "false"
                   category            NMTOKEN #IMPLIED>
<!ATTLIST vector   name                NMTOKEN #REQUIRED
                   type                CDATA #REQUIRED
                   size                NMTOKEN #REQUIRED
                   category            NMTOKEN #IMPLIED>

<!ATTLIST desc     name                NMTOKEN #REQUIRED
                   vector_size         CDATA #IMPLIED
                   convert             (true | false) #IMPLIED
                   error               NMTOKEN "GL_INVALID_ENUM"
                   category            NMTOKEN #IMPLIED>

<!ATTLIST value    name                CDATA #REQUIRED
                   category            NMTOKEN #IMPLIED>
<!ATTLIST range    from                NMTOKEN #REQUIRED
                   to                  NMTOKEN #REQUIRED
                   base                NMTOKEN #IMPLIED
                   category            NMTOKEN #IMPLIED>

=== ArcticaProject/vcxsrv/mesalib/src/mesa/main/APIspec.xml
<?xml version="1.0"?>
<!DOCTYPE apispec SYSTEM "APIspec.dtd">

<!-- A function is generated from a template.  Multiple functions can be
     generated from a single template with different arguments.  For example,
     glColor3f can be generated from

     <function name="Color3f" template="Color" gltype="GLfloat" vector_size="3" expand_vector="true"/>

     and glColor4iv can be generated from

     <function name="Color4iv" template="Color" gltype="GLint" vector_size="4"/>

     In a template, there are <desc>s that describe the properties of
     parameters.  A <desc> can enumerate the valid values of a parameter.  It
     can also specify the error code when an invalid value is given, and etc.
     By nesting <desc>s, they can create dependency between parameters.

     A function can be marked as external.  It means that the function cannot
     be dispatched to the corresponding mesa function, if one exists, directly,
     and requires an external implementation.
-->

<apispec>

<template name="Color">
	<proto>
		<return type="void"/>
		<vector name="v" type="const GLtype *" size="dynamic">
			<param name="red" type="GLtype"/>
			<param name="green" type="GLtype"/>
			<param name="blue" type="GLtype"/>
			<param name="alpha" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="ClipPlane">
	<proto>
		<return type="void"/>
		<param name="plane" type="GLenum"/>
		<vector name="equation" type="const GLtype *" size="4"/>
	</proto>
</template>

<template name="CullFace">
	<proto>
		<return type="void"/>
		<param name="mode" type="GLenum"/>
	</proto>
</template>

<template name="Fog">
	<proto>
		<return type="void"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="FrontFace">
	<proto>
		<return type="void"/>
		<param name="mode" type="GLenum"/>
	</proto>
</template>

<template name="Hint">
	<proto>
		<return type="void"/>
		<param name="target" type="GLenum"/>
		<param name="mode" type="GLenum"/>
	</proto>
</template>

<template name="Light">
	<proto>
		<return type="void"/>
		<param name="light" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="LightModel">
	<proto>
		<return type="void"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="LineWidth">
	<proto>
		<return type="void"/>
		<param name="width" type="GLtype"/>
	</proto>
</template>

<template name="Material">
	<proto>
		<return type="void"/>
		<param name="face" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="PointSize">
	<proto>
		<return type="void"/>
		<param name="size" type="GLtype"/>
	</proto>
</template>

<template name="PointSizePointer">
	<proto>
		<return type="void"/>
		<param name="type" type="GLenum"/>
		<param name="stride" type="GLsizei"/>
		<param name="pointer" type="const GLvoid *"/>
	</proto>
</template>

<template name="Scissor">
	<proto>
		<return type="void"/>
		<param name="x" type="GLint"/>
		<param name="y" type="GLint"/>
		<param name="width" type="GLsizei"/>
		<param name="height" type="GLsizei"/>
	</proto>
</template>

<template name="ShadeModel">
	<proto>
		<return type="void"/>
		<param name="mode" type="GLenum"/>
	</proto>
</template>

<template name="TexParameter">
	<proto>
		<return type="void"/>
		<param name="target" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="TexImage2D">
	<proto>
		<return type="void"/>
		<param name="target" type="GLenum"/>
		<param name="level" type="GLint"/>
		<param name="internalFormat" type="GLint"/> <!-- should be GLenum -->
		<param name="width" type="GLsizei"/>
		<param name="height" type="GLsizei"/>
		<param name="border" type="GLint"/>
		<param name="format" type="GLenum"/>
		<param name="type" type="GLenum"/>
		<param name="pixels" type="const GLvoid *"/>
	</proto>
</template>

<template name="TexEnv">
	<proto>
		<return type="void"/>
		<param name="target" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="TexGen">
	<proto>
		<return type="void"/>
		<param name="coord" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="const GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="Clear">
	<proto>
		<return type="void"/>
		<param name="mask" type="GLbitfield"/>
	</proto>
</template>

<template name="ClearColor">
	<proto>
		<return type="void"/>
		<param name="red" type="GLtype"/>
		<param name="green" type="GLtype"/>
		<param name="blue" type="GLtype"/>
		<param name="alpha" type="GLtype"/>
	</proto>
</template>

<template name="ClearStencil">
	<proto>
		<return type="void"/>
		<param name="s" type="GLint"/>
	</proto>
</template>

<template name="ClearDepth">
	<proto>
		<return type="void"/>
		<param name="depth" type="GLtype"/>
	</proto>
</template>

<template name="StencilMask">
	<proto>
		<return type="void"/>
		<param name="mask" type="GLuint"/>
	</proto>
</template>

<template name="StencilMaskSeparate">
	<proto>
		<return type="void"/>
		<param name="face" type="GLenum"/>
		<param name="mask" type="GLuint"/>
	</proto>
</template>

<template name="ColorMask">
	<proto>
		<return type="void"/>
		<param name="red" type="GLboolean"/>
		<param name="green" type="GLboolean"/>
		<param name="blue" type="GLboolean"/>
		<param name="alpha" type="GLboolean"/>
	</proto>
</template>

<template name="DepthMask">
	<proto>
		<return type="void"/>
		<param name="flag" type="GLboolean"/>
	</proto>
</template>

<template name="Disable">
	<proto>
		<return type="void"/>
		<param name="cap" type="GLenum"/>
	</proto>
</template>

<!-- it is exactly the same as Disable -->
<template name="Enable">
	<proto>
		<return type="void"/>
		<param name="cap" type="GLenum"/>
	</proto>
</template>

<template name="Finish">
	<proto>
		<return type="void"/>
	</proto>
</template>

<template name="Flush">
	<proto>
		<return type="void"/>
	</proto>
</template>

<template name="AlphaFunc">
	<proto>
		<return type="void"/>
		<param name="func" type="GLenum"/>
		<param name="ref" type="GLtype"/>
	</proto>
</template>

<template name="BlendFunc">
	<proto>
		<return type="void"/>
		<param name="sfactor" type="GLenum"/>
		<param name="dfactor" type="GLenum"/>
	</proto>
</template>

<template name="LogicOp">
	<proto>
		<return type="void"/>
		<param name="opcode" type="GLenum"/>
	</proto>
</template>

<template name="StencilFunc">
	<proto>
		<return type="void"/>
		<param name="func" type="GLenum"/>
		<param name="ref" type="GLint"/>
		<param name="mask" type="GLuint"/>
	</proto>
</template>

<template name="StencilFuncSeparate">
	<proto>
		<return type="void"/>
		<param name="face" type="GLenum"/>
		<param name="func" type="GLenum"/>
		<param name="ref" type="GLint"/>
		<param name="mask" type="GLuint"/>
	</proto>
</template>

<template name="StencilOp">
	<proto>
		<return type="void"/>
		<param name="fail" type="GLenum"/>
		<param name="zfail" type="GLenum"/>
		<param name="zpass" type="GLenum"/>
	</proto>
</template>

<template name="StencilOpSeparate">
	<proto>
		<return type="void"/>
		<param name="face" type="GLenum"/>
		<param name="fail" type="GLenum"/>
		<param name="zfail" type="GLenum"/>
		<param name="zpass" type="GLenum"/>
	</proto>
</template>

<template name="DepthFunc">
	<proto>
		<return type="void"/>
		<param name="func" type="GLenum"/>
	</proto>
</template>

<template name="PixelStore">
	<proto>
		<return type="void"/>
		<param name="pname" type="GLenum"/>
		<param name="param" type="GLtype"/>
	</proto>
</template>

<template name="ReadPixels" direction="get">
	<proto>
		<return type="void"/>
		<param name="x" type="GLint"/>
		<param name="y" type="GLint"/>
		<param name="width" type="GLsizei"/>
		<param name="height" type="GLsizei"/>
		<param name="format" type="GLenum"/>
		<param name="type" type="GLenum"/>
		<param name="pixels" type="GLvoid *"/>
	</proto>
</template>

<template name="GetClipPlane" direction="get">
	<proto>
		<return type="void"/>
		<param name="plane" type="GLenum"/>
		<vector name="equation" type="GLtype *" size="4"/>
	</proto>
</template>

<template name="GetError" direction="get">
	<proto>
		<return type="GLenum"/>
	</proto>
</template>

<!-- template for GetFloatv, GetIntegerv, GetBoolean, and GetFixedv -->
<template name="GetState" direction="get">
	<proto>
		<return type="void"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="GLtype *" size="dynamic"/>
	</proto>
	<!-- param checking is done in mesa -->
</template>

<template name="GetLight" direction="get">
	<proto>
		<return type="void"/>
		<param name="light" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="GLtype *" size="dynamic"/>
	</proto>
</template>

<template name="GetMaterial" direction="get">
	<proto>
		<return type="void"/>
		<param name="face" type="GLenum"/>
		<param name="pname" type="GLenum"/>
		<vector name="params" type="GLtype *" size="dynamic">
			<param name="param" type="GLtype"/>
		</vector>
	</proto>
</template>

<template name="GetString" direction="get">
	<proto>
		<return type="const GLubyte *"/>
		<param name="name" type="GLenum"/>
	</proto>
</template>

<template name="GetTexEnv" direction="get">
	<proto>
		<return type="void"/>
